name: Build Application

runs:
  using: composite

  steps:
  - name: Check out repository
    uses: actions/checkout@v4

  - name: Set up Python 3.10.14
    uses: actions/setup-python@v5
    with:
      python-version: '3.10.14'

  - name: Install poetry
    uses: snok/install-poetry@v1
    with:
      virtualenvs-in-project: true

  - name: Load cached dependencies
    uses: actions/cache@v4
    id: cached-dependencies
    with:
      path: .venv
      key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

  - name: Install dependencies
    if: steps.cached-dependencies.outputs.cache-hit != 'true'
    run: make install
    shell: bash
